# The apiVersion and kind fields are required because a kustomize plugin configuration objects are also Kubernetes objects.
apiVersion: apps.kruise.io/v1alpha1
kind: ResourceDistributionGenerator
metadata:
  name: rdname
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./plugins/function
resource:
  resourceKind: ConfigMap
  resourceName: cmname22
  envs:
    - a.env
  files:
    - file.properties
  literals:
    - JAVA_HOME=/opt/java/jdk
  resourceOptions:
    annotations:
      dashboard: "1"
    immutable: true
options:
  labels:
    app.kubernetes.io/name: "app1"
targets:
  includedNamespaces:
    - ns-1
    - ns-2
  namespaceLabelSelector:
    matchLabels:
      group: "test"
    matchExpressions:
      - key: exc
        operator: NotIn
        values:
          - abc
          - e